### ISSUE TITLE
What would be the way to pass cookies with requests?

### ISSUE THREAD

**Issue by jemmaengz1202** [alex-cory/use-http#115]
Is there a way to pass cookies with requests?
In axios, for example, one would do someting like this:
```javascript
axios.create({
  withCredentials: true
})
```

And, using Fetch Api:
```javascript
fetch('https://example.com', {
  credentials: 'include'  
})
```

Is there an option to send and recieve cookies to/from the server?

**Comment by alex-cory** [comment]
Is `credentials: 'include'` not working? That's how you should do it

**Comment by alex-cory** [comment]
In the [`fetch docs`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) it says:
> By default, fetch won't send or receive any cookies from the server, resulting in unauthenticated requests if the site relies on maintaining a user session (to send cookies, the credentials init option must be set).
Since Aug 25, 2017. The spec changed the default credentials policy to same-origin.

Are you testing in Chrome? If so, you need to have the `credentials: 'include'` or `credentials: 'same-origin'` set. Here's a [video](https://www.youtube.com/watch?v=J3w-G6NBxSc) explaining it. You can also refer to the [`Request.credentials docs`](https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials).

**Comment by alex-cory** [comment]
Closing this. If the issue persists or if this is still not working for some reason, please don't hesitate to reopen this issue!
