### ISSUE TITLE
SSR  - Weird issue with 'loading'

### ISSUE THREAD

**Issue by niicojs** [alex-cory/use-http#137]
**Describe the bug**
Server side, I'm getting `loading === true` even if I'm not firing any request. 
I tried putting `{ onMount: false, loading: false }`.

**Expected behavior**
Loading should be false if no request is made. Moreover, it seems the lib does not do anything server side, so loading should be ever set.

**Comment by alex-cory** [comment]
Currently, it doesn't make any requests when on the server. This feature has not been implemented yet which is why loading is set to true by default. Many times people try to iterate over data that may or may not be available yet due to a loading state. i.e.

loading = true
fetch the data
loading = false
if (!loading) display data <- would error here because there's no data

Currently we don't have the fetch request get executed until it is on the client.

**Comment by niicojs** [comment]
In my case, I'm handling a "save" button using `use-http`. So I have a save button with `disabled = saving`.
`saving` beeing the loading state of the post request. Right now, server side, it's rendering a disabled button which shouldn't happend.

**Comment by alex-cory** [comment]
Okay, I will change this

**Comment by alex-cory** [comment]
This should be fixed. See `v0.1.96`. If the issue persists, let me know and I'll have another look.
