### ISSUE TITLE
POST with body has body added to url

### ISSUE THREAD

**Issue by thomassuckow** [alex-cory/use-http#176]
**Describe the bug**
POST with body has body added to url

**⚠️ Make a Codesandbox ⚠️**
https://codesandbox.io/s/brave-noyce-wnjx9

**To Reproduce**
Make a post fetch with a JSON Body

**Expected behavior**
The request should be made to the specified URL, not the URL with the body appended.

**Comment by alex-cory** [comment]
Will fix ASAP. Thanks for the bug report! ❤️

**Comment by alex-cory** [comment]
Alright, found the bug and am curious your thoughts on this.
This works
```js
  const { loading, error, data } = useFetch(
    `https://httpbin.org/post`,
    {
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json"
      },
      method: "POST",
      body: { width: 100 } // notice the no JSON.stringify()
    },
    []
  )
```
The reason this doesn't work is because of the way relative routes are handled.
```js
  const { loading, error, data, post } = useFetch(
    `https://httpbin.org/post`,
    {
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json"
      },
      method: "POST",
      body: { width: 100 } // notice the no JSON.stringify()
    },
    []
  )

  post('/this-route-is-a-string', { this: 'is a body' })
  // and also
  post({ this: 'is a body' })
```
The example above with a relative route, the 1st param is a string. I can change this to require JSON.stringify when using useFetch the way you have it if this is the desired behavior. I can also make it work with either, but adds more complexity to the implementation. Thoughts?

**Comment by thomassuckow** [comment]
Since `fetch()` requires the body to be stringified, I would expect useFetch to also require body to be stringified. I don't understand why the `body` option would ever affect the URL.

**Comment by alex-cory** [comment]
Ok, I will make it so.

But the reason it's getting appended to the body is because under the hood, we use the `post` here. The post has 2 ways it can be called. `post('/route', { body })` or `post({ body })`. The way we do this is check to see if the first param is a `string`, if it is, append it to the url, and the 2nd arg is the body. If it is not a `string` then it's just a route. Since you're stringifying the body in this case, it thinks it's a route.

It's basically saying
```js
useEffect(() => {
  post(JSON.strinfigy(body))
}, [])
```
but the if the first argument is a string, it thinks it's a route.

Does that make more sense now?

**Comment by alex-cory** [comment]
This is now fixed. Please checkout `v0.2.8`. If there issue persists, comment here and I'll reopen the issue.
