### ISSUE TITLE
is the graphql support worth maintaining

### ISSUE THREAD

**Issue by dagda1** [alex-cory/use-http#40]
I hope this question does not come across as rude, it really is not meant to be.

I did a spike with GraphQL a while ago but I'm sort of curious where you see use-http fit into the ecosystem.

If I am using apollo or urql, would I not just use that?

Please feel free to shoot me down.  This is just me being curious.

**Comment by alex-cory** [comment]
So I could be wrong here, but is the only reason they use `client` is because of versatility between frameworks? Such as react, vue, angular? From the [`client.js`](https://github.com/FormidableLabs/urql/blob/master/src/client.ts) it looks like all the things they manage there could be done without a `Client` class which I think makes things simpler for the end user. I see this as a smaller, drop-in replacement for something like Apollo

**Comment by alex-cory** [comment]
Also, I find the syntax to be nicer to read, because it makes the queries/mutations actionable. As in, it basically makes them into a JS function.
```js
function QueryComponent() {
  const request = useQuery`
    query Todos($userID string!) {
      todos(userID: $userID) {
        id
        title
      }
    }
  `

  const getTodosForUser = id => request.query({ userID: id })

  return (
    <>
      <button onClick={() => getTodosForUser('theUsersID')}>Get User's Todos</button>
      {request.loading ? 'Loading...' : <pre>{request.data}</pre>}
    </>
  )
}
```
I'm open to discussing this though.
